name: "Kehua Inverter"
version: "0.2.1"
image: ghcr.io/voyanti/ha-kehua
slug: "ha-kehua"
description: "Kehua Inverter"
init: false
startup: application
boot: auto
url: "https://github.com/Voyanti/ha-kehua"
arch:
  - aarch64
  - amd64
options:
  servers:
    - name: "kehua1"
      serialnum: "unknown"
      server_type: "KEHUA_INVERTER"
      connected_client: "client1"
      modbus_id: 1  # default for kehua?
  clients:
    - name: "client1"
      type: "TCP"
      host: "192.168.1.91"
      port: 502
  pause_interval_seconds: 10
  sleep_over_midnight: true
  sleep_midnight_minutes: 10
  mqtt_host: "localhost"
  mqtt_port: 1884
  # mqtt_host: "core-mosquitto"
  # mqtt_port: 1883
  mqtt_user: "mqtt"
  mqtt_password: "mqtt-users"
  mwtt_ha_discovery_topic: "homeassistant"
  mqtt_base_topic: "modbus"
schema:
  servers:
    - name: str
      serialnum: str
      server_type: list(KEHUA_INVERTER)
      connected_client: str
      modbus_id: int(0,255)
      # PT: int?
      # CT: int?
  clients:
    - name: str
      type: list(TCP|RTU)
      host: str?
      port: str?
      baudrate: int?
      bytesize: int?
      parity: bool?
      stopbits: int?
  pause_interval_seconds: float
  sleep_over_midnight: bool
  sleep_midnight_minutes: int
  mqtt_host: str
  mqtt_port: port
  mqtt_user: str
  mqtt_password: password
  mwtt_ha_discovery_topic: str
  mqtt_base_topic: str
