name: "Kehua Inverter"
version: "0.1.3"
slug: "voyanti_kehua"
description: "Kehua Inverter"
init: false
startup: application
boot: auto
url: "https://github.com/Voyanti/ha-kehua"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  servers:
    - name: "Kehua Inverter 1"
      ha_display_name: "KH1"
      serialnum: "unknown"
      server_type: "KEHUA_INVERTER"
      connected_client: "Client1"
      modbus_id: 1  # default for kehua?
  clients:
    - name: "ModbusTCP"
      ha_display_name: "Client1"
      type: "TCP"
      host: "192.168.1.91"
      port: 502
  # mqtt_host: "localhost"
  # mqtt_port: 1884
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: "mqtt"
  mqtt_password: "mqtt"
  mwtt_ha_discovery_topic: "homeassistant"
  mqtt_base_topic: "modbus"
schema:
  servers:
    - name: str
      ha_display_name: str
      serialnum: str
      server_type: list(KEHUA_INVERTER)
      connected_client: str
      modbus_id: int(0,255)
  clients:
    - name: str
      ha_display_name: str
      type: list(TCP|RTU)
      host: str?
      port: int?
      baudrate: int?
      bytesize: int?
      parity: bool?
      stopbits: int?
  mqtt_host: str
  mqtt_port: port
  mqtt_user: str
  mqtt_password: password
  mwtt_ha_discovery_topic: str
  mqtt_base_topic: str
