from .enums import DataType, DeviceClass, Parameter, RegisterTypes

not_PCS_parameters = {
    # All except PCS
    "PV1 Voltage": {
        "addr": 0 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "V",
        "device_class": DeviceClass.VOLTAGE,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "PV1 DC Current": {
        "addr": 3 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "A",
        "device_class": DeviceClass.CURRENT,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "PV1 Power": {
        "addr": 51 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "kW",
        "device_class": DeviceClass.POWER,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "PV Daily Power Generation": {
        "addr": 62 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "kWh",
        "device_class": DeviceClass.ENERGY,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
}
atess_parameters: dict[str, Parameter] = {
    ###############################
    # Available on all models:
    ###############################
    "Serial Number": {
        "addr": 180 + 1,
        "count": 6,
        "dtype": DataType.UTF8,
        "device_class": DeviceClass.ENUM,
        "multiplier": 1,
        "unit": "",
        "register_type": RegisterTypes.HOLDING_REGISTER,
    },  # TODO count 5? p30
    # On/Off State
    "Device On/Off": {
        "addr": 0 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 1,
        "unit": "",
        "device_class": DeviceClass.ENUM,
        "register_type": RegisterTypes.HOLDING_REGISTER,
    },
    # Voltage and Current Measurements
    "PV Voltage": {
        "addr": 80 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "V",
        "device_class": DeviceClass.VOLTAGE,
        "register_type": RegisterTypes.HOLDING_REGISTER,
    },
    "Battery Voltage": {
        "addr": 81 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "V",
        "device_class": DeviceClass.VOLTAGE,
        "register_type": RegisterTypes.HOLDING_REGISTER,
    },
    "Battery Current": {
        "addr": 82 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "A",
        "device_class": DeviceClass.CURRENT,
        "register_type": RegisterTypes.HOLDING_REGISTER,
    },
    "PV Current": {
        "addr": 83 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "A",
        "device_class": DeviceClass.CURRENT,
        "register_type": RegisterTypes.HOLDING_REGISTER,
    },
    "Battery Power": {
        "addr": 17 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "kW",
        "device_class": DeviceClass.POWER,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Battery Percentage": {
        "addr": 47 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "device_class": DeviceClass.BATTERY,
        "multiplier": 1,
        "unit": "%",
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    # Output Voltages
    "Output Voltage U": {
        "addr": 84 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "V",
        "device_class": DeviceClass.VOLTAGE,
        "register_type": RegisterTypes.HOLDING_REGISTER,
    },
    "Output Voltage V": {
        "addr": 85 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "V",
        "device_class": DeviceClass.VOLTAGE,
        "register_type": RegisterTypes.HOLDING_REGISTER,
    },
    "Output Voltage W": {
        "addr": 86 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "V",
        "device_class": DeviceClass.VOLTAGE,
        "register_type": RegisterTypes.HOLDING_REGISTER,
    },
    # Grid Currents
    "Grid Current U": {
        "addr": 87 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "A",
        "device_class": DeviceClass.CURRENT,
        "register_type": RegisterTypes.HOLDING_REGISTER,
    },
    "Grid Current V": {
        "addr": 88 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "A",
        "device_class": DeviceClass.CURRENT,
        "register_type": RegisterTypes.HOLDING_REGISTER,
    },
    "Grid Current W": {
        "addr": 89 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "A",
        "device_class": DeviceClass.CURRENT,
        "register_type": RegisterTypes.HOLDING_REGISTER,
    },
    # Grid Voltages
    "Grid Voltage UV": {
        "addr": 90 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "V",
        "device_class": DeviceClass.VOLTAGE,
        "register_type": RegisterTypes.HOLDING_REGISTER,
    },
    "Grid Voltage VW": {
        "addr": 91 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "V",
        "device_class": DeviceClass.VOLTAGE,
        "register_type": RegisterTypes.HOLDING_REGISTER,
    },
    "Grid Voltage WU": {
        "addr": 92 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "V",
        "device_class": DeviceClass.VOLTAGE,
        "register_type": RegisterTypes.HOLDING_REGISTER,
    },
    # Load Currents
    "Load Current U": {
        "addr": 93 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "A",
        "device_class": DeviceClass.CURRENT,
        "register_type": RegisterTypes.HOLDING_REGISTER,
    },
    "Load Current V": {
        "addr": 94 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "A",
        "device_class": DeviceClass.CURRENT,
        "register_type": RegisterTypes.HOLDING_REGISTER,
    },
    "Load Current W": {
        "addr": 95 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "A",
        "device_class": DeviceClass.CURRENT,
        "register_type": RegisterTypes.HOLDING_REGISTER,
    },
    # Input registers
    "Hardware Version": {
        "addr": 270 + 1,
        "count": 10,
        "dtype": DataType.UTF8,
        "device_class": DeviceClass.ENUM,
        "multiplier": 1,
        "unit": "",
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Battery Voltage": {
        "addr": 1 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "V",
        "device_class": DeviceClass.VOLTAGE,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Battery Current": {
        "addr": 2 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "A",
        "device_class": DeviceClass.CURRENT,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Battery Power": {
        "addr": 17 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "kW",
        "device_class": DeviceClass.POWER,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    ###############################
}


PCS_parameters = {  # battery inverters
    "Battery Discharge Cutoff": {
        "addr": 47 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "device_class": DeviceClass.ENUM,
        "multiplier": 1,
        "unit": "%",
        "register_type": RegisterTypes.HOLDING_REGISTER,
    },
    "Frequency Shift Enable": {
        "addr": 79 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "device_class": DeviceClass.ENUM,
        "multiplier": 1,
        "unit": "",
        "register_type": RegisterTypes.HOLDING_REGISTER,
    },  # 0: false, 1 = mode1, 2= mode2
    "Power factor symbol": {
        "addr": 22 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 1,
        "unit": "",
        "device_class": DeviceClass.ENUM,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Power factor": {
        "addr": 23 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.001,
        "unit": "",
        "device_class": DeviceClass.ENUM,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    # Battery. NOTE Actually all types have this holding register
    "SOC Up Limit": {
        "addr": 66 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "device_class": DeviceClass.BATTERY,
        "multiplier": 1,
        "unit": "%",
        "register_type": RegisterTypes.HOLDING_REGISTER,
    },
    "SOC Down Limit": {
        "addr": 67 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "device_class": DeviceClass.BATTERY,
        "multiplier": 1,
        "unit": "%",
        "register_type": RegisterTypes.HOLDING_REGISTER,
    },
    "Charge Current Limit": {
        "addr": 154 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "device_class": DeviceClass.CURRENT,
        "multiplier": 0.1,
        "unit": "A",
        "register_type": RegisterTypes.HOLDING_REGISTER,
        "min": 0,
        "max": 10000,
    },
    "Discharge Current Limit": {
        "addr": 155 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "device_class": DeviceClass.CURRENT,
        "multiplier": 0.1,
        "unit": "A",
        "register_type": RegisterTypes.HOLDING_REGISTER,
        "min": 0,
        "max": 10000,
    },
    "Charge Cutoff SOC": {
        "addr": 178 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "device_class": DeviceClass.BATTERY,
        "multiplier": 1,
        "unit": "%",
        "register_type": RegisterTypes.HOLDING_REGISTER,
        "min": 0,
        "max": 100,
    },
    # PCS
    "Output Voltage UV": {
        "addr": 4 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "V",
        "device_class": DeviceClass.VOLTAGE,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Output Voltage VW": {
        "addr": 5 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "V",
        "device_class": DeviceClass.VOLTAGE,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Output Voltage WU": {
        "addr": 6 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "V",
        "device_class": DeviceClass.VOLTAGE,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Bypass Current U": {
        "addr": 7 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "A",
        "device_class": DeviceClass.CURRENT,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Bypass Current V": {
        "addr": 8 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "A",
        "device_class": DeviceClass.CURRENT,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Bypass Current W": {
        "addr": 9 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "A",
        "device_class": DeviceClass.CURRENT,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Output Frequency": {
        "addr": 16 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.01,
        "unit": "Hz",
        "device_class": DeviceClass.FREQUENCY,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Bypass Apparent Power": {
        "addr": 18 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "kVA",
        "device_class": DeviceClass.POWER,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Bypass Active Power": {
        "addr": 19 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "kW",
        "device_class": DeviceClass.POWER,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Bypass Reactive Power": {
        "addr": 20 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "kVar",
        "device_class": DeviceClass.POWER,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Grid Frequency": {
        "addr": 21 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.01,
        "unit": "Hz",
        "device_class": DeviceClass.FREQUENCY,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Output Apparent Power": {
        "addr": 78 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "kVA",
        "device_class": DeviceClass.POWER,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Output Active Power": {
        "addr": 79 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "kW",
        "device_class": DeviceClass.POWER,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Output Reactive Power": {
        "addr": 80 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "kVar",
        "device_class": DeviceClass.POWER,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Daily Power Consumption": {
        "addr": 82 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "kWh",
        "device_class": DeviceClass.ENERGY,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Daily Power From Grid": {
        "addr": 88 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "kWh",
        "device_class": DeviceClass.ENERGY,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Daily Power To Grid": {
        "addr": 94 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "kWh",
        "device_class": DeviceClass.ENERGY,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Output Current U": {
        "addr": 135 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "A",
        "device_class": DeviceClass.CURRENT,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Output Current V": {
        "addr": 136 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "A",
        "device_class": DeviceClass.CURRENT,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Output Current W": {
        "addr": 137 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "A",
        "device_class": DeviceClass.CURRENT,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    # HPS/PCS/HPSTL model registers
    "Load Apparent Power": {
        "addr": 48 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "kVA",
        "device_class": DeviceClass.POWER,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Load Active Power": {
        "addr": 49 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "kW",
        "device_class": DeviceClass.POWER,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Load Reactive Power": {
        "addr": 50 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "kVar",
        "device_class": DeviceClass.POWER,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Load Power Factor": {
        "addr": 52 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.001,
        "unit": "",
        "device_class": DeviceClass.POWER_FACTOR,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Load Current A": {
        "addr": 53 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "A",
        "device_class": DeviceClass.CURRENT,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Load Current B": {
        "addr": 54 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "A",
        "device_class": DeviceClass.CURRENT,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Load Current C": {
        "addr": 55 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "A",
        "device_class": DeviceClass.CURRENT,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Output Voltage U": {
        "addr": 56 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "V",
        "device_class": DeviceClass.VOLTAGE,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Output Voltage V": {
        "addr": 57 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "V",
        "device_class": DeviceClass.VOLTAGE,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Output Voltage W": {
        "addr": 58 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "V",
        "device_class": DeviceClass.VOLTAGE,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
}

PBD_parameters = {
    # PBD
    "PV2 Voltage": {
        "addr": 105 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "V",
        "device_class": DeviceClass.VOLTAGE,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "PV2 DC Current": {
        "addr": 106 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "A",
        "device_class": DeviceClass.CURRENT,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "PV2 Power": {
        "addr": 107 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "kW",
        "device_class": DeviceClass.POWER,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "PV Total Power": {
        "addr": 108 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "kW",
        "device_class": DeviceClass.POWER,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Output Voltage": {
        "addr": 109 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "V",
        "device_class": DeviceClass.VOLTAGE,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Output Current": {
        "addr": 110 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "A",
        "device_class": DeviceClass.CURRENT,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "Output Power": {
        "addr": 113 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "kW",
        "device_class": DeviceClass.POWER,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "PV Module Temperature": {
        "addr": 114 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "°C",
        "device_class": DeviceClass.TEMPERATURE,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "PV3 Voltage": {
        "addr": 123 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "V",
        "device_class": DeviceClass.VOLTAGE,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "PV4 Voltage": {
        "addr": 124 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "V",
        "device_class": DeviceClass.VOLTAGE,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "PV5 Voltage": {
        "addr": 125 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "V",
        "device_class": DeviceClass.VOLTAGE,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "PV3 DC Current": {
        "addr": 126 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "A",
        "device_class": DeviceClass.CURRENT,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "PV4 DC Current": {
        "addr": 127 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "A",
        "device_class": DeviceClass.CURRENT,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "PV5 DC Current": {
        "addr": 128 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "A",
        "device_class": DeviceClass.CURRENT,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "PV3 Power": {
        "addr": 132 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "kW",
        "device_class": DeviceClass.POWER,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "PV4 Power": {
        "addr": 133 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "kW",
        "device_class": DeviceClass.POWER,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
    "PV5 Power": {
        "addr": 134 + 1,
        "count": 1,
        "dtype": DataType.U16,
        "multiplier": 0.1,
        "unit": "kW",
        "device_class": DeviceClass.POWER,
        "register_type": RegisterTypes.INPUT_REGISTER,
    },
}
